project:
  type: website
  output-dir: ./docs/
website:
  title: "SGEng6e.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - contributions.qmd
      - contact.qmd
      - app.qmd
format:
  html:
    theme: cosmo
    toc: true
